import type { ToolSpec } from "../types.js";
import {
  asRecord,
  compactObject,
  readNumber,
  readString,
  requireString,
} from "../helpers.js";
import { privateRateLimit, publicRateLimit } from "../common.js";

function normalize(response: {
  endpoint: string;
  requestTime: string;
  data: unknown;
}): Record<string, unknown> {
  return {
    endpoint: response.endpoint,
    requestTime: response.requestTime,
    data: response.data,
  };
}

export function registerGridTools(): ToolSpec[] {
  return [
    {
      name: "grid_get_orders",
      module: "bot-grid",
      description:
        "[OKX API — server-side grid] Query grid trading bot list. Use status='active' for running bots, status='history' for completed/stopped bots. " +
        "Covers Spot Grid, Contract Grid, and Moon Grid. " +
        "Private endpoint. Rate limit: 20 req/2s per UID.",
      isWrite: false,
      inputSchema: {
        type: "object",
        properties: {
          algoOrdType: {
            type: "string",
            enum: ["grid", "contract_grid", "moon_grid"],
            description: "grid=Spot, contract_grid=Contract, moon_grid=Moon",
          },
          status: {
            type: "string",
            enum: ["active", "history"],
            description: "active=running (default); history=stopped",
          },
          instId: {
            type: "string",
            description: "e.g. BTC-USDT",
          },
          algoId: {
            type: "string",
          },
          after: {
            type: "string",
            description: "Pagination: before this algo ID",
          },
          before: {
            type: "string",
            description: "Pagination: after this algo ID",
          },
          limit: {
            type: "number",
            description: "Max results (default 100)",
          },
        },
        required: ["algoOrdType"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const algoOrdType = requireString(args, "algoOrdType");
        const status = readString(args, "status") ?? "active";
        const path =
          status === "history"
            ? "/api/v5/tradingBot/grid/orders-algo-history"
            : "/api/v5/tradingBot/grid/orders-algo-pending";
        const response = await context.client.privateGet(
          path,
          compactObject({
            algoOrdType,
            instId: readString(args, "instId"),
            algoId: readString(args, "algoId"),
            after: readString(args, "after"),
            before: readString(args, "before"),
            limit: readNumber(args, "limit"),
          }),
          privateRateLimit("grid_get_orders", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_get_order_details",
      module: "bot-grid",
      description:
        "[OKX API — server-side grid] Query details of a single grid trading bot by its algo ID. " +
        "Returns configuration, current status, PnL, and position info. " +
        "Private endpoint. Rate limit: 20 req/2s per UID.",
      isWrite: false,
      inputSchema: {
        type: "object",
        properties: {
          algoOrdType: {
            type: "string",
            enum: ["grid", "contract_grid", "moon_grid"],
            description: "grid=Spot, contract_grid=Contract, moon_grid=Moon",
          },
          algoId: {
            type: "string",
          },
        },
        required: ["algoOrdType", "algoId"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privateGet(
          "/api/v5/tradingBot/grid/orders-algo-details",
          {
            algoOrdType: requireString(args, "algoOrdType"),
            algoId: requireString(args, "algoId"),
          },
          privateRateLimit("grid_get_order_details", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_get_sub_orders",
      module: "bot-grid",
      description:
        "[OKX API — server-side grid] Query individual sub-orders (grid trades) generated by a grid bot. " +
        "Use type='filled' for executed trades, type='live' for pending orders. " +
        "Private endpoint. Rate limit: 20 req/2s per UID.",
      isWrite: false,
      inputSchema: {
        type: "object",
        properties: {
          algoOrdType: {
            type: "string",
            enum: ["grid", "contract_grid", "moon_grid"],
            description: "grid=Spot, contract_grid=Contract, moon_grid=Moon",
          },
          algoId: {
            type: "string",
          },
          type: {
            type: "string",
            enum: ["filled", "live"],
            description: "filled=executed trades (default); live=pending orders",
          },
          groupId: {
            type: "string",
          },
          after: {
            type: "string",
            description: "Pagination: before this order ID",
          },
          before: {
            type: "string",
            description: "Pagination: after this order ID",
          },
          limit: {
            type: "number",
            description: "Max results (default 100)",
          },
        },
        required: ["algoOrdType", "algoId"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privateGet(
          "/api/v5/tradingBot/grid/sub-orders",
          compactObject({
            algoOrdType: requireString(args, "algoOrdType"),
            algoId: requireString(args, "algoId"),
            type: readString(args, "type") ?? "filled",
            groupId: readString(args, "groupId"),
            after: readString(args, "after"),
            before: readString(args, "before"),
            limit: readNumber(args, "limit"),
          }),
          privateRateLimit("grid_get_sub_orders", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_create_order",
      module: "bot-grid",
      description:
        "[OKX API — server-side grid] Create a new grid trading bot managed by OKX servers. [CAUTION] Executes real trades and locks funds. " +
        "Supports Spot Grid ('grid') and Contract Grid ('contract_grid'). " +
        "For spot grid, provide quoteSz (invest in quote currency) or baseSz (invest in base currency). " +
        "For contract grids, provide direction, lever, and sz (number of contracts). " +
        "Private endpoint. Rate limit: 20 req/2s per UID.",
      isWrite: true,
      inputSchema: {
        type: "object",
        properties: {
          instId: {
            type: "string",
            description: "e.g. BTC-USDT",
          },
          algoOrdType: {
            type: "string",
            enum: ["grid", "contract_grid"],
            description: "grid=Spot, contract_grid=Contract",
          },
          maxPx: {
            type: "string",
            description: "Upper price boundary",
          },
          minPx: {
            type: "string",
            description: "Lower price boundary",
          },
          gridNum: {
            type: "string",
            description: "Grid levels (e.g. '10')",
          },
          runType: {
            type: "string",
            enum: ["1", "2"],
            description: "1=arithmetic (default); 2=geometric",
          },
          quoteSz: {
            type: "string",
            description: "Spot grid: invest in quote (e.g. USDT). Provide quoteSz or baseSz.",
          },
          baseSz: {
            type: "string",
            description: "Spot grid: invest in base (e.g. BTC). Provide quoteSz or baseSz.",
          },
          direction: {
            type: "string",
            enum: ["long", "short", "neutral"],
            description: "Required for contract_grid",
          },
          lever: {
            type: "string",
            description: "Leverage (e.g. '5'). Required for contract_grid.",
          },
          sz: {
            type: "string",
            description: "Margin amount in USDT for contract_grid (e.g. '50'). Minimum ~26 USDT. NOT number of contracts.",
          },
        },
        required: ["instId", "algoOrdType", "maxPx", "minPx", "gridNum"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privatePost(
          "/api/v5/tradingBot/grid/order-algo",
          compactObject({
            instId: requireString(args, "instId"),
            algoOrdType: requireString(args, "algoOrdType"),
            maxPx: requireString(args, "maxPx"),
            minPx: requireString(args, "minPx"),
            gridNum: requireString(args, "gridNum"),
            runType: readString(args, "runType"),
            quoteSz: readString(args, "quoteSz"),
            baseSz: readString(args, "baseSz"),
            direction: readString(args, "direction"),
            lever: readString(args, "lever"),
            sz: readString(args, "sz"),
          }),
          privateRateLimit("grid_create_order", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_get_ai_param",
      module: "bot-grid",
      description:
        "[OKX API] Get AI-recommended parameters for a grid strategy (price range, grid count, expected APY). " +
        "Useful for estimating parameters before creating a grid strategy. " +
        "Public endpoint. Rate limit: 20 req/2s.",
      isWrite: false,
      inputSchema: {
        type: "object",
        properties: {
          instId:      { type: "string", description: "e.g. BTC-USDT" },
          algoOrdType: { type: "string", enum: ["grid", "contract_grid", "moon_grid"], description: "Grid type" },
          direction:   { type: "string", enum: ["long", "short", "neutral"], description: "Required for contract_grid" },
          duration:    { type: "string", enum: ["7D", "30D", "180D"], description: "Back-test window (default: 7D)" },
        },
        required: ["instId", "algoOrdType"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.publicGet(
          "/api/v5/tradingBot/grid/ai-param",
          compactObject({
            instId:      requireString(args, "instId"),
            algoOrdType: requireString(args, "algoOrdType"),
            direction:   readString(args, "direction"),
            duration:    readString(args, "duration"),
          }),
          publicRateLimit("grid_get_ai_param", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_amend_tpsl",
      module: "bot-grid",
      description:
        "[OKX API — server-side grid] Modify take-profit and/or stop-loss prices for a running OKX grid strategy. " +
        "Private endpoint. Rate limit: 20 req/2s.",
      isWrite: true,
      inputSchema: {
        type: "object",
        properties: {
          algoId:      { type: "string" },
          instId:      { type: "string", description: "e.g. BTC-USDT or BTC-USDT-SWAP" },
          tpTriggerPx: { type: "string", description: "New take-profit trigger price" },
          slTriggerPx: { type: "string", description: "New stop-loss trigger price" },
        },
        required: ["algoId", "instId"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privatePost(
          "/api/v5/tradingBot/grid/amend-order-algo",
          compactObject({
            algoId:      requireString(args, "algoId"),
            instId:      requireString(args, "instId"),
            tpTriggerPx: readString(args, "tpTriggerPx"),
            slTriggerPx: readString(args, "slTriggerPx"),
          }),
          privateRateLimit("grid_amend_tpsl", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_adjust_investment",
      module: "bot-grid",
      description:
        "[OKX API — server-side grid] Add investment to a running OKX grid strategy. " +
        "allowReinvestProfit controls whether accumulated profits are included in the added investment (default: true). " +
        "[CAUTION] Modifies live strategy. Private endpoint. Rate limit: 20 req/2s.",
      isWrite: true,
      inputSchema: {
        type: "object",
        properties: {
          algoId:             { type: "string" },
          amt:                { type: "string", description: "Amount to add (USDT)" },
          allowReinvestProfit: { type: "string", enum: ["true", "false"], description: "Include grid profits in the investment (default: true)" },
        },
        required: ["algoId", "amt"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privatePost(
          "/api/v5/tradingBot/grid/adjust-investment",
          compactObject({
            algoId:              requireString(args, "algoId"),
            amt:                 requireString(args, "amt"),
            allowReinvestProfit: readString(args, "allowReinvestProfit"),
          }),
          privateRateLimit("grid_adjust_investment", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_withdraw_income",
      module: "bot-grid",
      description:
        "[OKX API — server-side grid] Withdraw accumulated profits from a running OKX grid strategy without stopping it. " +
        "[CAUTION] Modifies live strategy balance. Private endpoint. Rate limit: 20 req/2s.",
      isWrite: true,
      inputSchema: {
        type: "object",
        properties: {
          algoId: { type: "string" },
        },
        required: ["algoId"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privatePost(
          "/api/v5/tradingBot/grid/withdraw-income",
          { algoId: requireString(args, "algoId") },
          privateRateLimit("grid_withdraw_income", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_close_position",
      module: "bot-grid",
      description:
        "[OKX API — server-side grid] Close the open position held by a contract grid strategy (market or limit). " +
        "[CAUTION] Executes a real trade. Private endpoint. Rate limit: 20 req/2s.",
      isWrite: true,
      inputSchema: {
        type: "object",
        properties: {
          algoId:   { type: "string" },
          mktClose: { type: "boolean", description: "true=market close (default); false=limit close (requires px)" },
          px:       { type: "string", description: "Limit close price. Required when mktClose=false." },
        },
        required: ["algoId"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const mktClose = args["mktClose"] !== false;
        const response = await context.client.privatePost(
          "/api/v5/tradingBot/grid/close-position",
          compactObject({ algoId: requireString(args, "algoId"), mktClose, px: readString(args, "px") }),
          privateRateLimit("grid_close_position", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_get_positions",
      module: "bot-grid",
      description:
        "Query current positions held by a contract grid strategy. " +
        "Returns open position size, entry price, unrealized PnL, and margin info. " +
        "Private endpoint. Rate limit: 20 req/2s.",
      isWrite: false,
      inputSchema: {
        type: "object",
        properties: {
          algoId:      { type: "string" },
          algoOrdType: { type: "string", enum: ["contract_grid"], description: "Must be contract_grid" },
        },
        required: ["algoId", "algoOrdType"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privateGet(
          "/api/v5/tradingBot/grid/positions",
          {
            algoId:      requireString(args, "algoId"),
            algoOrdType: requireString(args, "algoOrdType"),
          },
          privateRateLimit("grid_get_positions", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_cancel_close_order",
      module: "bot-grid",
      description:
        "Cancel a pending limit close-position order placed by a contract grid strategy. " +
        "Use when you want to revoke a limit close that hasn't filled yet. " +
        "[CAUTION] Modifies live strategy. Private endpoint. Rate limit: 20 req/2s.",
      isWrite: true,
      inputSchema: {
        type: "object",
        properties: {
          algoId: { type: "string" },
          ordId:  { type: "string", description: "The close-position limit order ID to cancel" },
        },
        required: ["algoId", "ordId"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privatePost(
          "/api/v5/tradingBot/grid/cancel-close-order",
          { algoId: requireString(args, "algoId"), ordId: requireString(args, "ordId") },
          privateRateLimit("grid_cancel_close_order", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_compute_margin_balance",
      module: "bot-grid",
      description:
        "Compute the effect of adding or reducing margin for a contract grid strategy without actually changing it. " +
        "Returns estimated new leverage and liquidation price after the adjustment. " +
        "Private endpoint. Rate limit: 20 req/2s.",
      isWrite: false,
      inputSchema: {
        type: "object",
        properties: {
          algoId: { type: "string" },
          type:   { type: "string", enum: ["add", "reduce"], description: "add=add margin; reduce=withdraw margin" },
          amt:    { type: "string", description: "Amount to simulate (USDT)" },
        },
        required: ["algoId", "type", "amt"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privatePost(
          "/api/v5/tradingBot/grid/compute-margin-balance",
          { algoId: requireString(args, "algoId"), type: requireString(args, "type"), amt: requireString(args, "amt") },
          privateRateLimit("grid_compute_margin_balance", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_adjust_margin_balance",
      module: "bot-grid",
      description:
        "Add or reduce margin for a running contract grid strategy to change leverage and risk exposure. " +
        "type='add' deposits more margin (lowers leverage); type='reduce' withdraws margin (raises leverage). " +
        "[CAUTION] Modifies live position margin. Private endpoint. Rate limit: 20 req/2s.",
      isWrite: true,
      inputSchema: {
        type: "object",
        properties: {
          algoId: { type: "string" },
          type:   { type: "string", enum: ["add", "reduce"], description: "add=deposit more margin; reduce=withdraw margin" },
          amt:    { type: "string", description: "Amount to add or withdraw (USDT)" },
        },
        required: ["algoId", "type", "amt"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privatePost(
          "/api/v5/tradingBot/grid/margin-balance",
          { algoId: requireString(args, "algoId"), type: requireString(args, "type"), amt: requireString(args, "amt") },
          privateRateLimit("grid_adjust_margin_balance", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_stop_order",
      module: "bot-grid",
      description:
        "[OKX API — server-side grid] Stop a running OKX grid trading bot. [CAUTION] This will close or cancel the bot's orders. " +
        "For contract grids, stopType controls whether open positions are closed ('1') or only orders are cancelled ('2'). " +
        "Private endpoint. Rate limit: 20 req/2s per UID.",
      isWrite: true,
      inputSchema: {
        type: "object",
        properties: {
          algoId: {
            type: "string",
          },
          algoOrdType: {
            type: "string",
            enum: ["grid", "contract_grid", "moon_grid"],
            description: "grid=Spot, contract_grid=Contract, moon_grid=Moon",
          },
          instId: {
            type: "string",
            description: "e.g. BTC-USDT",
          },
          stopType: {
            type: "string",
            enum: ["1", "2", "3", "5", "6"],
            description: "1=stop+sell/close all; 2=stop+keep assets (default); 3=close at limit; 5=partial close; 6=stop without selling (smart arb)",
          },
        },
        required: ["algoId", "algoOrdType", "instId"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privatePost(
          "/api/v5/tradingBot/grid/stop-order-algo",
          [compactObject({
            algoId: requireString(args, "algoId"),
            algoOrdType: requireString(args, "algoOrdType"),
            instId: requireString(args, "instId"),
            stopType: readString(args, "stopType"),
          })],
          privateRateLimit("grid_stop_order", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_instant_trigger",
      module: "bot-grid",
      description:
        "[OKX API — server-side grid] Immediately trigger a pending grid strategy that was created with a trigger condition. " +
        "Useful when you want to force-start a grid bot without waiting for the trigger price or RSI condition to be met. " +
        "Optionally provide topUpAmt to top up additional funds at the moment of triggering. " +
        "[CAUTION] Activates a live strategy. Private endpoint. Rate limit: 20 req/2s.",
      isWrite: true,
      inputSchema: {
        type: "object",
        properties: {
          algoId:   { type: "string", description: "Grid strategy algo ID to trigger immediately" },
          topUpAmt: { type: "string", description: "Optional additional top-up amount (USDT) to add when triggering" },
        },
        required: ["algoId"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privatePost(
          "/api/v5/tradingBot/grid/order-instant-trigger",
          compactObject({
            algoId:   requireString(args, "algoId"),
            topUpAmt: readString(args, "topUpAmt"),
          }),
          privateRateLimit("grid_instant_trigger", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_compute_min_investment",
      module: "bot-grid",
      description:
        "[OKX API — public] Compute the minimum investment required to create a grid strategy with given parameters. " +
        "Use this before grid_create_order to confirm you have sufficient funds. " +
        "Returns minimum quoteSz/baseSz for spot grid, or minimum sz (margin USDT) for contract grid. " +
        "Public endpoint (no API key required). Rate limit: 20 req/2s.",
      isWrite: false,
      inputSchema: {
        type: "object",
        properties: {
          instId:      { type: "string", description: "e.g. BTC-USDT or BTC-USDT-SWAP" },
          algoOrdType: { type: "string", enum: ["grid", "contract_grid"], description: "grid=Spot, contract_grid=Contract" },
          maxPx:       { type: "string", description: "Upper price boundary" },
          minPx:       { type: "string", description: "Lower price boundary" },
          gridNum:     { type: "string", description: "Number of grid levels (e.g. '10')" },
          runType:     { type: "string", enum: ["1", "2"], description: "1=arithmetic; 2=geometric" },
          direction:   { type: "string", enum: ["long", "short", "neutral"], description: "Required for contract_grid" },
          lever:       { type: "string", description: "Leverage (e.g. '5'). Required for contract_grid." },
          basePos:     { type: "boolean", description: "Whether to hold base currency position at start (contract_grid only)" },
        },
        required: ["instId", "algoOrdType", "maxPx", "minPx", "gridNum", "runType"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.publicPost(
          "/api/v5/tradingBot/grid/min-investment",
          compactObject({
            instId:      requireString(args, "instId"),
            algoOrdType: requireString(args, "algoOrdType"),
            maxPx:       requireString(args, "maxPx"),
            minPx:       requireString(args, "minPx"),
            gridNum:     requireString(args, "gridNum"),
            runType:     requireString(args, "runType"),
            direction:   readString(args, "direction"),
            lever:       readString(args, "lever"),
            basePos:     args["basePos"] !== undefined ? Boolean(args["basePos"]) : undefined,
          }),
          publicRateLimit("grid_compute_min_investment", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_rsi_back_testing",
      module: "bot-grid",
      description:
        "[OKX API — public] Run RSI back-testing to find how many times an RSI trigger condition was met in historical data. " +
        "Useful for evaluating RSI-based grid trigger strategies before going live. " +
        "Returns triggerNum (number of times the RSI condition fired). " +
        "Public endpoint (no API key required). Rate limit: 20 req/2s.",
      isWrite: false,
      inputSchema: {
        type: "object",
        properties: {
          instId:      { type: "string", description: "e.g. BTC-USDT" },
          timeframe:   { type: "string", enum: ["3m", "5m", "15m", "30m", "1H", "4H", "1D"], description: "Candlestick timeframe for RSI calculation" },
          thold:       { type: "string", description: "RSI threshold value (0–100, e.g. '30' for oversold)" },
          timePeriod:  { type: "string", description: "RSI period in candles (e.g. '14')" },
          triggerCond: { type: "string", enum: ["cross_up", "cross_down", "above", "below", "cross"], description: "Trigger condition (default: cross_down)" },
          duration:    { type: "string", description: "Back-test duration in days (e.g. '7')" },
        },
        required: ["instId", "timeframe", "thold", "timePeriod"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.publicGet(
          "/api/v5/tradingBot/public/rsi-back-testing",
          compactObject({
            instId:      requireString(args, "instId"),
            timeframe:   requireString(args, "timeframe"),
            thold:       requireString(args, "thold"),
            timePeriod:  requireString(args, "timePeriod"),
            triggerCond: readString(args, "triggerCond"),
            duration:    readString(args, "duration"),
          }),
          publicRateLimit("grid_rsi_back_testing", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_max_quantity",
      module: "bot-grid",
      description:
        "[OKX API — public] Get the maximum number of grid levels allowed for an instrument, price range, and grid type. " +
        "Use before grid_create_order to validate that your gridNum does not exceed the platform limit. " +
        "Returns maxGridQty. Public endpoint (no API key required). Rate limit: 20 req/2s.",
      isWrite: false,
      inputSchema: {
        type: "object",
        properties: {
          instId:      { type: "string", description: "e.g. BTC-USDT or BTC-USDT-SWAP" },
          algoOrdType: { type: "string", enum: ["grid", "contract_grid"], description: "grid=Spot, contract_grid=Contract" },
          runType:     { type: "string", enum: ["1", "2"], description: "1=arithmetic; 2=geometric" },
          maxPx:       { type: "string", description: "Upper price boundary" },
          minPx:       { type: "string", description: "Lower price boundary" },
          lever:       { type: "string", description: "Leverage (required for contract_grid)" },
        },
        required: ["instId", "algoOrdType", "runType", "maxPx", "minPx"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.publicGet(
          "/api/v5/tradingBot/grid/grid-quantity",
          compactObject({
            instId:      requireString(args, "instId"),
            algoOrdType: requireString(args, "algoOrdType"),
            runType:     requireString(args, "runType"),
            maxPx:       requireString(args, "maxPx"),
            minPx:       requireString(args, "minPx"),
            lever:       readString(args, "lever"),
          }),
          publicRateLimit("grid_max_quantity", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_liquidate_price",
      module: "bot-grid",
      description:
        "[OKX API — server-side grid] Estimate the liquidation price for a contract grid strategy before placing it. " +
        "Useful for risk assessment: given a price range, leverage, and investment size, returns the estimated forced liquidation price. " +
        "Private endpoint. Rate limit: 20 req/2s.",
      isWrite: false,
      inputSchema: {
        type: "object",
        properties: {
          instId:    { type: "string", description: "e.g. BTC-USDT-SWAP" },
          sz:        { type: "string", description: "Margin amount in USDT (e.g. '100')" },
          lever:     { type: "string", description: "Leverage (e.g. '5')" },
          direction: { type: "string", enum: ["long", "short", "neutral"], description: "Contract grid direction" },
          gridNum:   { type: "string", description: "Number of grid levels (e.g. '10')" },
          maxPx:     { type: "string", description: "Upper price boundary" },
          minPx:     { type: "string", description: "Lower price boundary" },
          runType:   { type: "string", enum: ["1", "2"], description: "1=arithmetic; 2=geometric" },
          basePos:   { type: "boolean", description: "Whether to open a base position at start" },
        },
        required: ["instId", "sz", "lever"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privateGet(
          "/api/v5/tradingBot/grid/liquidate-price",
          compactObject({
            instId:    requireString(args, "instId"),
            sz:        requireString(args, "sz"),
            lever:     requireString(args, "lever"),
            direction: readString(args, "direction"),
            gridNum:   readString(args, "gridNum"),
            maxPx:     readString(args, "maxPx"),
            minPx:     readString(args, "minPx"),
            runType:   readString(args, "runType"),
            basePos:   args["basePos"] !== undefined ? Boolean(args["basePos"]) : undefined,
          }),
          privateRateLimit("grid_liquidate_price", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_amend_basic_param",
      module: "bot-grid",
      description:
        "[OKX API — server-side grid] Amend the basic parameters (price range, grid count) of a running grid strategy. " +
        "Use this to adjust the grid range or number of grids without stopping the bot. " +
        "Optionally provide topupAmount to add extra investment alongside the parameter change. " +
        "[CAUTION] Modifies live strategy. Private endpoint. Rate limit: 20 req/2s.",
      isWrite: true,
      inputSchema: {
        type: "object",
        properties: {
          algoId:      { type: "string", description: "Grid strategy algo ID" },
          maxPx:       { type: "string", description: "New upper price boundary" },
          minPx:       { type: "string", description: "New lower price boundary" },
          gridNum:     { type: "string", description: "New number of grid levels" },
          topupAmount: { type: "string", description: "Optional additional funds to add alongside the parameter change (USDT)" },
        },
        required: ["algoId", "maxPx", "minPx", "gridNum"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privatePost(
          "/api/v5/tradingBot/grid/amend-algo-basic-param",
          compactObject({
            algoId:      requireString(args, "algoId"),
            maxPx:       requireString(args, "maxPx"),
            minPx:       requireString(args, "minPx"),
            gridNum:     requireString(args, "gridNum"),
            topupAmount: readString(args, "topupAmount"),
          }),
          privateRateLimit("grid_amend_basic_param", 20),
        );
        return normalize(response);
      },
    },
  ];
}
