import type { ToolSpec } from "../types.js";
import {
  asRecord,
  compactObject,
  readNumber,
  readString,
  requireString,
} from "../helpers.js";
import { privateRateLimit } from "../common.js";

function normalize(response: {
  endpoint: string;
  requestTime: string;
  data: unknown;
}): Record<string, unknown> {
  return {
    endpoint: response.endpoint,
    requestTime: response.requestTime,
    data: response.data,
  };
}

export function registerGridTools(): ToolSpec[] {
  return [
    {
      name: "grid_get_orders",
      module: "bot",
      description:
        "Query grid trading bot list. Use status='active' for running bots, status='history' for completed/stopped bots. " +
        "Covers Spot Grid, Contract Grid, and Moon Grid. Private endpoint. Rate limit: 20 req/2s per UID.",
      isWrite: false,
      inputSchema: {
        type: "object",
        properties: {
          algoOrdType: {
            type: "string",
            enum: ["grid", "contract_grid", "moon_grid"],
            description:
              "Grid type. 'grid': Spot Grid. 'contract_grid': Contract Grid. 'moon_grid': Moon Grid.",
          },
          status: {
            type: "string",
            enum: ["active", "history"],
            description:
              "Query active (running) bots or history (stopped/completed). Default: 'active'.",
          },
          instId: {
            type: "string",
            description: "Instrument ID filter, e.g. 'BTC-USDT'.",
          },
          algoId: {
            type: "string",
            description: "Filter by specific bot algo ID.",
          },
          after: {
            type: "string",
            description: "Pagination: bots created earlier than this algo ID.",
          },
          before: {
            type: "string",
            description: "Pagination: bots created later than this algo ID.",
          },
          limit: {
            type: "number",
            description: "Number of results, default 100, max 100.",
          },
        },
        required: ["algoOrdType"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const algoOrdType = requireString(args, "algoOrdType");
        const status = readString(args, "status") ?? "active";
        const path =
          status === "history"
            ? "/api/v5/tradingBot/grid/orders-algo-history"
            : "/api/v5/tradingBot/grid/orders-algo-pending";
        const response = await context.client.privateGet(
          path,
          compactObject({
            algoOrdType,
            instId: readString(args, "instId"),
            algoId: readString(args, "algoId"),
            after: readString(args, "after"),
            before: readString(args, "before"),
            limit: readNumber(args, "limit"),
          }),
          privateRateLimit("grid_get_orders", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_get_order_details",
      module: "bot",
      description:
        "Query details of a single grid trading bot by its algo ID. " +
        "Returns configuration, current status, PnL, and position info. " +
        "Private endpoint. Rate limit: 20 req/2s per UID.",
      isWrite: false,
      inputSchema: {
        type: "object",
        properties: {
          algoOrdType: {
            type: "string",
            enum: ["grid", "contract_grid", "moon_grid"],
            description: "Grid type of the bot.",
          },
          algoId: {
            type: "string",
            description: "Bot algo ID to query.",
          },
        },
        required: ["algoOrdType", "algoId"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privateGet(
          "/api/v5/tradingBot/grid/orders-algo-details",
          {
            algoOrdType: requireString(args, "algoOrdType"),
            algoId: requireString(args, "algoId"),
          },
          privateRateLimit("grid_get_order_details", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_get_sub_orders",
      module: "bot",
      description:
        "Query individual sub-orders (grid trades) generated by a grid bot. " +
        "Use type='filled' for executed trades, type='live' for pending orders. " +
        "Private endpoint. Rate limit: 20 req/2s per UID.",
      isWrite: false,
      inputSchema: {
        type: "object",
        properties: {
          algoOrdType: {
            type: "string",
            enum: ["grid", "contract_grid", "moon_grid"],
            description: "Grid type of the bot.",
          },
          algoId: {
            type: "string",
            description: "Bot algo ID whose sub-orders to query.",
          },
          type: {
            type: "string",
            enum: ["filled", "live"],
            description:
              "Sub-order type. 'filled': executed grid trades. 'live': pending open orders. Default: 'filled'.",
          },
          groupId: {
            type: "string",
            description: "Filter by sub-order group ID.",
          },
          after: {
            type: "string",
            description: "Pagination: sub-orders earlier than this order ID.",
          },
          before: {
            type: "string",
            description: "Pagination: sub-orders newer than this order ID.",
          },
          limit: {
            type: "number",
            description: "Number of results, default 100, max 100.",
          },
        },
        required: ["algoOrdType", "algoId"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privateGet(
          "/api/v5/tradingBot/grid/sub-orders",
          compactObject({
            algoOrdType: requireString(args, "algoOrdType"),
            algoId: requireString(args, "algoId"),
            type: readString(args, "type") ?? "filled",
            groupId: readString(args, "groupId"),
            after: readString(args, "after"),
            before: readString(args, "before"),
            limit: readNumber(args, "limit"),
          }),
          privateRateLimit("grid_get_sub_orders", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_create_order",
      module: "bot",
      description:
        "Create a new grid trading bot. [CAUTION] Executes real trades and locks funds. " +
        "Supports Spot Grid ('grid') and Contract Grid ('contract_grid'). " +
        "For spot grid, provide quoteSz (invest in quote currency) or baseSz (invest in base currency). " +
        "For contract grids, provide direction, lever, and sz (number of contracts). " +
        "Private endpoint. Rate limit: 20 req/2s per UID.",
      isWrite: true,
      inputSchema: {
        type: "object",
        properties: {
          instId: {
            type: "string",
            description: "Instrument ID, e.g. 'BTC-USDT'.",
          },
          algoOrdType: {
            type: "string",
            enum: ["grid", "contract_grid"],
            description:
              "Grid type. 'grid': Spot Grid. 'contract_grid': Contract Grid.",
          },
          maxPx: {
            type: "string",
            description: "Upper price boundary of the grid range.",
          },
          minPx: {
            type: "string",
            description: "Lower price boundary of the grid range.",
          },
          gridNum: {
            type: "string",
            description: "Number of grid levels (integer as string, e.g. '10').",
          },
          runType: {
            type: "string",
            enum: ["1", "2"],
            description:
              "Grid spacing type. '1': arithmetic (equal price intervals, default). '2': geometric (equal ratio intervals).",
          },
          quoteSz: {
            type: "string",
            description:
              "Investment amount in quote currency (e.g. USDT). For spot grid only. Provide quoteSz or baseSz, not both.",
          },
          baseSz: {
            type: "string",
            description:
              "Investment amount in base currency (e.g. BTC). For spot grid only. Provide quoteSz or baseSz, not both.",
          },
          direction: {
            type: "string",
            enum: ["long", "short", "neutral"],
            description:
              "Position direction for contract grid. Required for contract_grid.",
          },
          lever: {
            type: "string",
            description:
              "Leverage multiplier for contract grid (e.g. '5'). Required for contract_grid.",
          },
          sz: {
            type: "string",
            description:
              "Number of contracts to invest for contract grid. Required for contract_grid.",
          },
        },
        required: ["instId", "algoOrdType", "maxPx", "minPx", "gridNum"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privatePost(
          "/api/v5/tradingBot/grid/order-algo",
          compactObject({
            instId: requireString(args, "instId"),
            algoOrdType: requireString(args, "algoOrdType"),
            maxPx: requireString(args, "maxPx"),
            minPx: requireString(args, "minPx"),
            gridNum: requireString(args, "gridNum"),
            runType: readString(args, "runType"),
            quoteSz: readString(args, "quoteSz"),
            baseSz: readString(args, "baseSz"),
            direction: readString(args, "direction"),
            lever: readString(args, "lever"),
            sz: readString(args, "sz"),
          }),
          privateRateLimit("grid_create_order", 20),
        );
        return normalize(response);
      },
    },
    {
      name: "grid_stop_order",
      module: "bot",
      description:
        "Stop a running grid trading bot. [CAUTION] This will close or cancel the bot's orders. " +
        "For contract grids, stopType controls whether open positions are closed ('1') or only orders are cancelled ('2'). " +
        "Private endpoint. Rate limit: 20 req/2s per UID.",
      isWrite: true,
      inputSchema: {
        type: "object",
        properties: {
          algoId: {
            type: "string",
            description: "Bot algo ID to stop.",
          },
          algoOrdType: {
            type: "string",
            enum: ["grid", "contract_grid", "moon_grid"],
            description: "Grid type of the bot.",
          },
          instId: {
            type: "string",
            description: "Instrument ID, e.g. 'BTC-USDT'.",
          },
          stopType: {
            type: "string",
            enum: ["1", "2", "3", "5", "6"],
            description:
              "Stop behavior. '1': stop and sell/close position (spot: sell quote; contract: market close all). " +
              "'2': stop but keep position/assets (default). '3': stop and close at limit price. " +
              "'5': stop and partially close. '6': stop without selling spot (smart arbitrage).",
          },
        },
        required: ["algoId", "algoOrdType", "instId"],
      },
      handler: async (rawArgs, context) => {
        const args = asRecord(rawArgs);
        const response = await context.client.privatePost(
          "/api/v5/tradingBot/grid/stop-order-algo",
          [compactObject({
            algoId: requireString(args, "algoId"),
            algoOrdType: requireString(args, "algoOrdType"),
            instId: requireString(args, "instId"),
            stopType: readString(args, "stopType"),
          })],
          privateRateLimit("grid_stop_order", 20),
        );
        return normalize(response);
      },
    },
  ];
}
